### ISSUE TITLE
getting error when sending data to zabbix server 

### ISSUE THREAD

**Issue by suryabh4** [adubkov/py-zabbix#103]
I am testing a code snippet 

                    from pyzabbix import ZabbixMetric, ZabbixSender, ZabbixResponse
                    metrics= [ZabbixMetric('mme01', 'TEST', '20')]
                    ZabbixSender('10.46.224.5').send(metrics)

When I run this I get an error - 

Traceback (most recent call last):
  File "zabbix_sender.py", line 14, in <module>
    ZabbixSender('10.46.224.5').send(metrics)
  File "/usr/local/lib/python2.7/dist-packages/pyzabbix/sender.py", line 433, in send
    result.parse(self._chunk_send(metrics[m:m + self.chunk_size]))
  File "/usr/local/lib/python2.7/dist-packages/pyzabbix/sender.py", line 408, in _chunk_send
    logger.warn('Sending failed: %s', err.msg)
AttributeError: 'error' object has no attribute 'msg'

What am I missing ? How can diagnose the issue. I have connectivity to the IP "10.46.224.5" from my linux box.

**Comment by suryabh4** [comment]
Changed the code a little bit and now get a different error - 

     from pyzabbix import ZabbixMetric, ZabbixSender, ZabbixResponse
      metrics = []

       m= ZabbixMetric('mme01', 'TEST', 20)
       metrics.append(m)
       ZabbixSender('10.46.224.5').send(metrics)

AttributeError: 'ConnectionRefusedError' object has no attribute 'msg'

**Comment by josheschulz** [comment]
Heads up this looks like it was fixed by this commit: https://github.com/adubkov/py-zabbix/commit/515a1aa8de6293cd269d7f1a2d7219471c37ff49
