### ISSUE TITLE
Why always recieve {"failed": 1, "chunk": 1, "total": 1, "processed": 0, "time": "0.000045"}，Pls help on this

### ISSUE THREAD

**Issue by tlyw** [adubkov/py-zabbix#121]
[root@centos ~]# yum install zabbix-sender
[root@centos ~]# zabbix_sender -s "consul1" -z 127.0.0.1 -p 10051 -k "mongodb_conn" -o 1
Response from "127.0.0.1:10051": "processed: 1; failed: 0; total: 1; seconds spent: 0.000250"
sent: 1; skipped: 0; total: 1

[no data](https://github.com/petrushinvs/mongodb-zabbix-templates-4.0/issues/4#issue-464080077)
[mongodb- zabbix -templates-4.0 /mongod-db.py](https://github.com/petrushinvs/mongodb-zabbix-templates-4.0/blob/master/mongod-db.py)
```
ZBSERVER = 'localhost'
ZBPORT = 10051
packet = []
packet.append(ZabbixMetric(zbhost, "mongodb_conn", conn))
result = ZabbixSender(zabbix_server = ZBSERVER, zabbix_port = ZBPORT).send(packet)
print(result)  // {"failed": 1, "chunk": 1, "total": 1, "processed": 0, "time": "0.000045"}
print(packet) //  [{"host": "consul1 ", "value": "8", "key": "mongodb_conn"}]
```

* Zabbix 4.2

**Comment by adubkov** [comment]
Sorry, I haven't tested it with Zabbix 4.2. Usually when if failed it means that server can not accept metric, an example - that metric is not exist in zabbix. But in your case zabbix_sender seems to work, so it must be something else.

**Comment by tlyw** [comment]
[Simple examples are normal](https://github.com/petrushinvs/mongodb-zabbix-templates-4.0/issues/4#issuecomment-508692800)

Zabbix4.2->Zabbix4.0

zs.py
![image](https://user-images.githubusercontent.com/35353706/60711468-969ee180-9f47-11e9-91f1-5593bc3d2568.png)

[root@centos externalscripts]# ./zs.py
{"failed": 0, "chunk": 1, "total": 2, "processed": 2, "time": "0.000161"}
[{"host": "consul1", "value": "100", "key": "mongodb_conn"}, {"host": "consul1", "value": "1", "key": "mongodb_query"}]

It's strange. In theory, the effect should be the same.，but mongod-db.py -> {"failed": 16, "chunk": 1, "total": 16, "processed": 0, "time": "0.000326"}

Thank you ^_^
