### ISSUE TITLE
not possible to insert via zabbix send

### ISSUE THREAD

**Issue by michaelwulz** [adubkov/py-zabbix#134]
with an easy script it is not possible to update the key on the given hostname:

```
from  pyzabbix import ZabbixMetric, ZabbixSender
metrics = []

m = ZabbixMetric('paradox.states.system.power', 'battery', 10)
metrics.append(m)
pprint(metrics)

server = ZabbixSender('192.168.1.1','10051')
result = server.send(metrics)

```
with this given result:
**python3 battery.py 
[{"host": "paradox.states.system.power", "key": "battery", "value": "10"}]
Traceback (most recent call last):
  File "battery.py", line 13, in <module>
    result = server.send(metrics)
  File "/usr/local/lib/python3.6/dist-packages/pyzabbix/sender.py", line 443, in send
    result.parse(self._chunk_send(metrics[m:m + self.chunk_size]))
  File "/usr/local/lib/python3.6/dist-packages/pyzabbix/sender.py", line 408, in _chunk_send
    connection.connect(host_addr)
TypeError: an integer is required (got type str)**

what can i do?

**Comment by maksim77** [comment]
Just remove the quotes around the port in the line where you are initializing  server object. 

'10051' -> 10051
