### ISSUE TITLE
Zabbix discovery

### ISSUE THREAD

**Issue by smarmie** [adubkov/py-zabbix#71]
Hi,
Is there a way of using this module to send Zabbix discovery items?
Thanks.

**Comment by adubkov** [comment]
@smarmie I think so. Discovery is something you configure on server side, once server receive an items it discovery rule should work.

https://www.zabbix.com/documentation/3.0/manual/discovery/low_level_discovery

**Comment by smarmie** [comment]
Hi,
Sorry, I forgot to say I got it working, and to post here the "solution".
In my case, I have a passive discovery rule, with the key discovery.key and I populate it like this:
```
from pyzabbix import ZabbixMetric, ZabbixSender

discovery = {'data': [{'{#ITEM}': item} for item in items]}
metrics = list()
metrics.append(ZabbixMetric('hostname',
                            discovery.key,
                            json.dumps(discovery)))
result = ZabbixSender(use_config=True).send(metrics)
```
So the point is that you have the send the whole json to one key,
Maybe this helps someone.
